version: '3.3'

services: 
    database:
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: 'coronaData'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'superSicher123'
            MYSQL_ROOT_PASSWORD: 'nochVielSicherer1234!'
        networks: 
            - 'corona-net'
        volumes:
            - my-db:/var/lib/mysql

    importbackend:
        build: ./backend/import
        networks: 
            - 'corona-net'
        depends_on: 
            - 'database'

    exportbackend:
        build: ./backend/export
        networks: 
            - 'corona-net'
        depends_on: 
           - 'database'

    importfrontend:
        build: ./frontend/import
        networks: 
            - 'corona-net'
        ports: 
            - '443:443'
            - '8080:80'
        depends_on: 
            - 'database'

    exportfrontend:
        build: ./frontend/export
        networks: 
            - 'corona-net'
        ports: 
            - '442:443'
            - '8081:80'
        depends_on: 
            - 'database'

volumes:
    my-db:
networks: 
    corona-net:
        driver: bridge