version: '3.3'

services: 
    databse:
        container_name: 'Corona-Info-Database'
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: 'coronaData'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'superSicher123'
            MYSQL_ROOT_PASSWORD: 'nochVielSicherer1234!'
        networks: 
            - 'corona-net'
        volumes:
            - my-db:/var/lib/mysql

    importbackend:
        build: ./backend/import
        networks: 
            - 'corona-net'

    exportbackend:
        build: ./backend/export
        networks: 
            - 'corona-net'

    importfrontend:
        build: ./frontend/import
        networks: 
            - 'corona-net'
        ports: 
            - '4200:4200'

    exportfrontend:
        build: ./frontend/export
        networks: 
            - 'corona-net'
        ports: 
            - '4201:4200'

volumes:
    my-db:
networks: 
    corona-net:
        driver: bridge