version: '3.3'

services: 
    databse:
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: 'coronaData'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'superSicher123'
            MYSQL_ROOT_PASSWORD: 'nochVielSicherer1234!'
        ports: 
            - '3306:3306'
        expose: 
            - '3306'
        volumes:
            - my-db:/var/lib/mysql

volumes:
    my-db: