package com.f73.corona.backend.export.models;

public enum Province {
    BERLIN, BRANDENBURG, SAXONY_ANHALT, SAXONY, THURINGA, MECKLENBURG_WEST_POMERANIA, SCHLESWIG_HOLSTEIN, LOWER_SAXONY,  HAMBURG, BREMEN, HESSEN, RHINELAND_PALATINATE, BADEN_WURTTEMBERG, SAARLAND, BAVARIA, NORTH_RHINE_WESTPHALIA;

}
